### ISSUE TITLE
ほう，そう来たか

### ISSUE THREAD

**Issue by daddygongon** [shopippi/JP_README_generator#2]
悪くないですよ．最終の出力が綺麗なんで．
でも，READMEぐらいの長さが必要で，さらに，修正が何度も入るような文書の作成は，
command line入出力のinterfaceではしんどいです．

1. 雛形を提供して，そこに書き込んでいく，あるいは，
2. 内容だけをあるフォーマットにして用意しておいて，流し込む
 
方が筋が良さそうですね．

**Comment by shopippi** [comment]
@daddygongon 実際に、最終的に掲載するために出力したREADMEファイルをcloneした後に手で修正していました。。
CLI、GUIに関わらずREADMEを作るのであれば、別にこんなプログラムが無くても雛形のフォーマットで十分事足りたと思えば胸が痛いものです。。。

迅速なレビューありがとうございました。

**Comment by daddygongon** [comment]
ごめんなさい．胸が痛いコメントでしたでしょうか．私は，「いいね」と評価したコメントを書いたつもりでした．実際に何かを完成させることでより良いインターフェースが設計できるようになります．そのためのsuggestionのつもりでした．胸を痛めないでください．
